### ISSUE TITLE
make a short documentation (GPT)

### ISSUE THREAD

**Issue by DevAnDess** [Ahamidullin/PROJECT#5]

**Comment by DevAnDess** [comment]
**1** _Hubble Space Telescope Images_: Набор данных изображений, полученных с помощью космического телескопа Хаббл. Эти изображения включают в себя фотографии различных галактик, звездных скоплений, туманностей и других астрономических объектов.
 **2** _Mars Rover Photos_: Фотографии, сделанные роверами на Марсе (например, Curiosity Rover, Perseverance Rover). Этот набор данных содержит изображения марсианской поверхности, ландшафта, геологических образований и т. д.
 **3** _Near-Earth Object (NEO) Data_: Данные о близнецовидных объектах, таких как астероиды и кометы, которые могут приближаться к Земле. Этот набор данных включает характеристики объектов, их орбиты и другие параметры.
 **4** _Exoplanet Archive_: Данные об экзопланетах, которые были обнаружены вне Солнечной системы. Этот набор данных содержит информацию о свойствах экзопланет, таких как их радиусы, массы, орбиты и т. д.
 **5** _Astronomical Catalogs_: Различные астрономические каталоги, содержащие данные о звездах, галактиках, квазарах и других астрономических объектах. Эти данные могут включать в себя координаты, яркость, расстояние и другие характеристики объектов.

**Comment by DevAnDess** [comment]
надо выбрать 1 - 2 и там уже начинать писать, мы вроде все согласились с 3, поэтому начну с него

**Comment by yanantro** [comment]
взяла 4 тему Exoplanet Archive
